import 'package:flutter/material.dart';

Color mainColor = Colors.pink;
Color mainColorAccent = Colors.pinkAccent;
Color mainColor2 = const Color(0xFFFC5FB5);
Color messageColor = const Color(0xFFFF1586);
Color onlineColor = Colors.lightGreenAccent;
Color green = Colors.green;
Color red = Colors.redAccent;
Color backColor = const Color(0xFF49454F);
Color backColor2 = const Color(0xFF1C1B1F);
Color black = Colors.black;
Color black8 = Colors.black87;
Color grey = Colors.grey;
Color grey3 = Colors.grey.shade300;
Color grey4 = Colors.grey.shade400;
Color grey6 = Colors.grey.shade600;
Color grey7 = Colors.grey.shade700;
Color white = Colors.white;
Color white1 = Colors.white10;
Color whiteX = Colors.white12;
Color white5 = Colors.white54;
Color transparent = Colors.transparent;